package com.example.trabajointegrador.CentroMedico
import java.util.Scanner
fun main() {
    val read= Scanner(System.`in`)
    var paciente1 = Paciente("","",0,0,0.0,0.0,"")
    var medico1 = Medico("","",0,0,0,"")
    println("Ingresa el nombre del paciente.")
    paciente1.nombre=read.next()
    println("Ingresa el apellido del paciente.")
    paciente1.apellido=read.next()
    println("Ingresa la edad del paciente.")
    paciente1.edad=read.nextInt()
    println("Ingresa el dni del paciente.")
    paciente1.dni=read.nextInt()
    println("Ingresa el peso del paciente.")
    paciente1.peso=read.nextDouble()
    println("Ingresa la altura del paciente.")
    paciente1.altura=read.nextDouble()
    println("Ingresa el diagnóstico del paciente.")
    paciente1.diagnostico=read.next()
    println("***********************************")
    println(paciente1)
    println("Ingrese el nombre del médico.")
    medico1.nombre=read.next()
    println("Ingrese el apellido del médico.")
    medico1.apellido=read.next()
    println("Ingrese la edad del médico.")
    medico1.edad=read.nextInt()
    println("Ingrese el dni del médico.")
    medico1.dni=read.nextInt()
    println("Ingrese los años que tiene el médico como profesional.")
    medico1.aniosExperiencia=read.nextInt()
    println("Ingrese el doctorado del médico.")
    medico1.tipoDoctorado=read.next()
}