package com.example.trabajointegrador.CentroMedico
import java.util.Scanner
fun main() {
    val read= Scanner(System.`in`)
    var paciente1 = Paciente("","",0,0,0.0,0.0,"")
    println("Ingresa el nombre del paciente.")
    paciente1.nombre=read.next()
    println("Ingresa el apellido del paciente.")
    paciente1.apellido=read.next()
    println("Ingresa la edad del paciente.")
    paciente1.edad=read.nextInt()
    println("Ingresa el dni del paciente.")
    paciente1.dni=read.nextInt()
    println("Ingresa el peso del paciente.")
    paciente1.peso=read.nextDouble()
    println("Ingresa la altura del paciente.")
    paciente1.altura=read.nextDouble()
    println("Ingresa el diagnóstico del paciente.")
    paciente1.diagnostico=read.next()
    println("***********************************")
    println(paciente1.nombre)
    println(paciente1.apellido)
    println(paciente1.edad)
    println(paciente1.edad)
    println(paciente1.peso)
    println(paciente1.altura)
    println(paciente1.diagnostico)
}